/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_dynamodb_all_tables_region": "ca-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "websitefrm-dev",
            "region": "ca-central-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "webfrapp",
            "endpoint": "https://peahkqrnhj.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ]
};


export default awsmobile;
